version: '3.9'

services:
  django_project:
    build:
       dockerfile: DockerfileDjango
    ports:
      - '8022:8000'
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scraping_project:/code/scraping_project
    command: tail -f /dev/null 
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - project_network

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project_network

volumes:
  pgdata:

networks:
  project_network:
    driver: bridge

